version: "3"
services:
  db:
    container_name: '${PROJECT_NAME}_db'
    image: postgres:14
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - dimas_cars_backend_pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: '${PROJECT_NAME}_redis'
    image: redis:6
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - dimas_cars_backend_redisdata:/data
    restart: always

  backend:
    build:
      context: .
    ports:
      - 3005:3000
    volumes:
      - ./upload:/usr/src/app/upload
    depends_on:
      - db
      - redis
    restart: always

volumes:
  dimas_cars_backend_pgdata:
  dimas_cars_backend_redisdata:
