version: "3"
services:
  db:
    container_name: 'cars_db'
    image: postgres:14
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
    networks:
      - 'cars_internal'
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - cars_pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: 'cars_redis'
    image: redis:6
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - 'cars_internal'
    volumes:
      - cars_redisdata:/data
    restart: always

  #not needed at local
  backend:
    container_name: 'cars_back'
    build:
      context: .
    ports:
      - '${PORT}:3000'
    networks:
      - 'cars_internal'
    depends_on:
      - db
      - redis
    restart: always

volumes:
  cars_pgdata:
  cars_redisdata:

networks:
  cars_internal:
    driver: bridge
